// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmZnarCu00-SLgcgdLmS3wdVd9ldTMJ4',
    appId: '1:850392123121:web:e1f0b8cc7d8ce1ba6d4b50',
    messagingSenderId: '850392123121',
    projectId: 'dummyproject-a9fbe',
    authDomain: 'dummyproject-a9fbe.firebaseapp.com',
    storageBucket: 'dummyproject-a9fbe.appspot.com',
    measurementId: 'G-DFCYK816CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1hJ4OutseDbqHeeP-6RpD54zDuY7_Gg',
    appId: '1:850392123121:android:44f1fc40435510336d4b50',
    messagingSenderId: '850392123121',
    projectId: 'dummyproject-a9fbe',
    storageBucket: 'dummyproject-a9fbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDM8SpcwJlJS0_Jr1s5TFLvg7O-Z9rASg',
    appId: '1:850392123121:ios:fbae7321059133d56d4b50',
    messagingSenderId: '850392123121',
    projectId: 'dummyproject-a9fbe',
    storageBucket: 'dummyproject-a9fbe.appspot.com',
    iosBundleId: 'com.example.dummyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDM8SpcwJlJS0_Jr1s5TFLvg7O-Z9rASg',
    appId: '1:850392123121:ios:fbae7321059133d56d4b50',
    messagingSenderId: '850392123121',
    projectId: 'dummyproject-a9fbe',
    storageBucket: 'dummyproject-a9fbe.appspot.com',
    iosBundleId: 'com.example.dummyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHmZnarCu00-SLgcgdLmS3wdVd9ldTMJ4',
    appId: '1:850392123121:web:1120ff01cf325b696d4b50',
    messagingSenderId: '850392123121',
    projectId: 'dummyproject-a9fbe',
    authDomain: 'dummyproject-a9fbe.firebaseapp.com',
    storageBucket: 'dummyproject-a9fbe.appspot.com',
    measurementId: 'G-6PJP1H0K8D',
  );
}
